CREATE DATABASE customer_shopping_behavior_db;

SELECT * FROM customer_shopping_behavior_clean;

-- Q1- What is the total revenue generated by male v/s female customers?
-- Q2- Which customers used discount but still spent more than average purchase amount?
-- Q3- Which are the top 5 products with the highest average review rating?
-- Q4- Compare the average purchase amount between standard and express shipping.
-- Q5- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
-- Q6- Which 5 products have the highest percentage of purchases with discounts applied?
-- Q7- Segment customers into new, returning and loyal based on their total number of previous purchases, and show the count of each segment.
-- Q8- What are the three most purchased products within each category?
-- Q9- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Q10- What is the revenue contribution of each age group?



-- Q1- What is the total revenue generated by male v/s female customers?

SELECT gender, SUM(purchase_amount) AS revenue_generated
FROM customer_shopping_behavior_clean
GROUP BY gender;



-- Q2- Which customers used discount but still spent more than average purchase amount?

WITH avg_purchase_amt AS( 
	SELECT customer_id, purchase_amount, discount_applied,
		ROUND(AVG(purchase_amount) OVER() ,2) AS avg_purchase_amount
	FROM customer_shopping_behavior_clean
 )
SELECT customer_id
FROM avg_purchase_amt
WHERE purchase_amount > avg_purchase_amount
	AND discount_applied = 1;



-- Q3- Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating), 2) AS average_review_rating
FROM customer_shopping_behavior_clean
GROUP BY item_purchased 
ORDER BY average_review_rating DESC
LIMIT 5;


-- Q4- Compare the average purchase amount between standard and express shipping.

SELECT shipping_type, AVG(purchase_amount)
FROM customer_shopping_behavior_clean
WHERE shipping_type IN ("Standard", "Express")
GROUP BY shipping_type;


-- Q5- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, AVG(purchase_amount), SUM(purchase_amount)
FROM customer_shopping_behavior_clean
GROUP BY subscription_status;


-- Q6- Which 5 products have the highest percentage of purchases with discounts applied?

WITH counts AS(
		SELECT item_purchased,  SUM(discount_applied) AS each_cat_cnt, COUNT(*) AS total
		FROM customer_shopping_behavior_clean
		GROUP BY item_purchased
)
SELECT item_purchased, ROUND(100.0 * (each_cat_cnt / total), 2) AS fraction_of_purchases
FROM counts
ORDER BY fraction_of_purchases DESC
LIMIT 5;


-- -- Q7- Segment customers into new, returning and loyal based on their total number of previous purchases, and show the count of each segment.

SELECT SUM(CASE WHEN previous_purchases = 1 THEN 1 ELSE 0 END) AS new_customers,
	SUM(CASE WHEN previous_purchases > 1 AND previous_purchases <= 10 THEN 1 ELSE 0 END) AS returning_customers,
	SUM(CASE WHEN previous_purchases > 10 THEN 1 ELSE 0 END) AS loyal_customers
FROM customer_shopping_behavior_clean;



-- Q8- What are the three most purchased products within each category?

SELECT category, item_purchased, category_total
FROM(SELECT category, item_purchased, COUNT(item_purchased) AS category_total, 
		RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS rnk
	FROM customer_shopping_behavior_clean
	GROUP BY category, item_purchased 
	)t
WHERE rnk <= 3



-- Q9- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
	SUM(CASE WHEN previous_purchases > 5 AND subscription_status  = 1 THEN 1 ELSE 0 END) AS repeat_buyers_with_subscription,
	SUM(CASE WHEN previous_purchases > 5 AND subscription_status  = 0 THEN 1 ELSE 0 END) AS repeat_buyers_no_subscription
FROM customer_shopping_behavior_clean;
	


-- Q10- What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS revenue
FROM customer_shopping_behavior_clean
GROUP BY age_group 
ORDER BY revenue DESC;

	












